const I={box:'<path d="M3 8l9-5 9 5-9 5-9-5z"/><path d="M3 8v8l9 5 9-5V8"/>',mega:'<path d="M3 11v2a2 2 0 002 2h1l3 5V4L6 9H5a2 2 0 00-2 2z"/><path d="M13 8a4 4 0 010 8"/>',cam:'<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7l2-3h4l2 3"/><circle cx="12" cy="13.5" r="3.5"/>',bag:'<path d="M6 8h12l1 12H5L6 8z"/><path d="M9 8V6a3 3 0 016 0v2"/>',shirt:'<path d="M8 4L3 7l2 3 2-1v11h10V9l2 1 2-3-5-3-1 2H9L8 4z"/>',case:'<rect x="3" y="8" width="18" height="11" rx="2"/><path d="M9 8V6a2 2 0 012-2h2a2 2 0 012 2v2"/><path d="M3 13h18"/>',chat:'<path d="M4 5h16v11H9l-5 4V5z"/><path d="M8 9h8M8 12h5"/>',book:'<path d="M4 5c3-1.5 6-1.5 8 0v14c-2-1.5-5-1.5-8 0V5z"/><path d="M20 5c-3-1.5-6-1.5-8 0v14c2-1.5 5-1.5 8 0V5z"/>',code:'<path d="M8 8l-4 4 4 4"/><path d="M16 8l4 4-4 4"/><path d="M13 5l-2 14"/>',spark:'<path d="M12 3l2 6 6 2-6 2-2 6-2-6-6-2 6-2 2-6z"/>',play:'<circle cx="12" cy="12" r="10"/><path d="M10 8l6 4-6 4V8z"/>',film:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M8 5v14M16 5v14"/>',scissors:'<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M20 4L8.5 15.5M20 20L8.5 8.5"/>',bookmark:'<path d="M6 4h12v16l-6-4-6 4V4z"/>',shield:'<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6l8-3z"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="M15 9l-2 5-5 2 2-5 5-2z"/>',access:'<circle cx="12" cy="4.5" r="2"/><path d="M5 8h14M12 8v6M12 14l-3 6M12 14l3 6"/>'};

const DATA=[
{id:'dropship',name:'Dropshipping',color:'#FF6B4A',icon:I.box,age:'16+',
 desc:'Sell products online without holding inventory — your supplier ships directly to the customer.',
 intro:{what:'You build an online store, list a supplier\'s products, and advertise them. When someone orders, your supplier ships the package straight to the buyer. You never touch the product or buy stock upfront.',
 money:'The gap between what the customer pays you and what the supplier charges, minus ad spend. A product that costs you $15 and sells for $39 leaves $24 gross — roughly half of that usually goes back into ads.',
 cost:'$50–$120 for month one: store subscription (free trial available) plus a small test ad budget.',
 time:'8–15 hours a week',
 income:'Most people make $0 for the first two months — that is the learning phase. Those who stick with it and learn to advertise typically reach $150–$800/month after six months. Very few go far beyond that, and not by accident.',
 risk:'The real danger is burning cash on ads with zero sales. Only spend what you are fully prepared to lose, and kill a campaign that is not working after three days.',
 fit:'Good for people curious about how advertising actually works, and willing to fail a few times first.',
 legal:'You are selling to real customers, so consumer protection law applies: accurate product descriptions, clear shipping times, and a written refund policy. Payment processors (Stripe, PayPal, Shopify Payments) require an account holder aged 18+ — under 18 this must run through a parent\'s account and, in most places, their business registration.'},
 videoUrl:'https://www.youtube.com/watch?v=snswA3W7Xac',
 platforms:[
  {n:'AutoDS',w:'All-in-one dropshipping automation: product research, auto price/stock updates, and automatic order fulfilment across suppliers.',u:'https://www.autods.com/',p:'Paid, free trial'},
  {n:'Shopify',w:'The store platform itself — checkout, payments, product pages and apps.',u:'https://www.shopify.com/',p:'Paid, free trial'},
  {n:'CJdropshipping',w:'Supplier network with warehouses worldwide, often faster shipping than ordering direct from marketplaces.',u:'https://cjdropshipping.com/',p:'Free to join'},
  {n:'Spocket',w:'Supplier marketplace focused on US and EU suppliers, so shipping takes days instead of weeks.',u:'https://www.spocket.co/',p:'Free tier'},
  {n:'DSers',w:'Order automation built around AliExpress suppliers.',u:'https://www.dsers.com/',p:'Free tier'},
  {n:'Meta Ads Manager',w:'Where you actually run Instagram and Facebook ads and read the results.',u:'https://business.facebook.com/',p:'Free tool, you pay for ads'},
  {n:'TikTok Ads Manager',w:'Ad platform where most teen-audience products are tested first.',u:'https://ads.tiktok.com/',p:'Free tool, you pay for ads'}],
 steps:[
  {title:'Find a niche and a product worth testing',text:'Look for a product that solves one small, real problem. Check demand on Google Trends and TikTok, and compare 3–5 suppliers before choosing. Shipping time matters more than price.',tool:'ChatGPT',toolUse:'Filters product ideas and analyses competitors in minutes',video:'how to find a winning dropshipping product'},
  {title:'Build your first store',text:'Keep it simple and clean. Focus everything on one product page that explains clearly why someone should buy from you: real photos, proof, and an honest returns policy.',tool:'Shopify Magic',toolUse:'Writes product descriptions and builds a sales page in seconds',video:'how to build a shopify store step by step'},
  {title:'Run your first ad campaign',text:'Install your tracking pixel, then run a small campaign on a low daily budget. The goal here is to learn what works, not to make a profit.',tool:'AdCreative.ai',toolUse:'Generates dozens of ad variations and shows which one wins',video:'first facebook ad campaign for dropshipping'},
  {title:'Deliver service and keep customers',text:'Reply fast, send shipping updates before people ask, and request a review after every good order. Reviews are what make your future ads cheaper.',tool:'Tidio AI',toolUse:'Chatbot that answers customers automatically around the clock',video:'ecommerce customer service automation'}]},

{id:'affiliate',name:'Affiliate Marketing',color:'#F4B740',icon:I.mega,age:'14+',
 desc:'Recommend other companies\' products and earn a commission on every sale through your link.',
 intro:{what:'You join a company\'s affiliate programme, get a personal tracking link, and recommend the product in your content. Anyone who buys through your link is credited to you and you earn a percentage. You never handle the product, shipping or support.',
 money:'Commission per sale — usually 3%–10% on physical products, and 20%–50% on digital products and courses.',
 cost:'$0. One social account is enough to start.',
 time:'5–10 hours a week',
 income:'Slow at the start: usually nothing for the first three months, because you need an audience first. People who publish consistently often reach $80–$500/month after a year.',
 risk:'Financial risk is near zero, but the real risk is trust: recommending a bad product for the commission burns the audience you spent months building.',
 fit:'Good if you enjoy making content and can wait months for the first result.',
 legal:'Disclosure is legally required in most countries (FTC rules in the US, similar rules elsewhere): every paid or commissioned recommendation must be clearly labelled. Most affiliate programmes also require members to be 18+, so under 18 you normally apply through a parent.'},
 videoUrl:'https://www.youtube.com/watch?v=Q17FB80ioA0',
 platforms:[
  {n:'Amazon Associates',w:'The easiest place to start — link to almost any product on Amazon.',u:'https://affiliate-program.amazon.com/',p:'Free'},
  {n:'Impact',w:'Large network connecting creators with well-known brands and higher commissions.',u:'https://impact.com/',p:'Free for partners'},
  {n:'ShareASale (Awin)',w:'Thousands of merchant programmes across most niches.',u:'https://www.shareasale.com/',p:'Free for partners'},
  {n:'Awin',w:'Global affiliate network, strong in Europe and the UK.',u:'https://www.awin.com/',p:'Free for partners'},
  {n:'CJ Affiliate',w:'One of the oldest networks, mostly bigger retail brands.',u:'https://www.cj.com/',p:'Free for partners'},
  {n:'ClickBank',w:'Digital products and courses with high commission rates.',u:'https://www.clickbank.com/',p:'Free'},
  {n:'PartnerStack',w:'Affiliate programmes for software and SaaS tools — recurring commissions.',u:'https://www.partnerstack.com/',p:'Free for partners'}],
 steps:[
  {title:'Pick a programme in your niche',text:'Choose a topic you genuinely know, then join a programme with a fair commission and a product you would recommend even without being paid.',tool:'Claude',toolUse:'Compares affiliate programmes and explains the terms in plain language',video:'how to choose affiliate programs beginners'},
  {title:'Build a content asset you own',text:'Start a channel, page or blog and publish consistently. This is what keeps sending people to your links months after you post.',tool:'Canva AI',toolUse:'Designs consistent templates for posts and thumbnails',video:'how to start a content channel from scratch'},
  {title:'Make honest recommendation content',text:'Show real use and say what is not great about the product too. Honest reviews convert far better than ads — and keep you out of trouble.',tool:'CapCut AI',toolUse:'Edits review videos quickly with automatic captions',video:'how to film a product review video'},
  {title:'Track conversions and double down',text:'Check which links and posts actually produce sales, then make more of that instead of trying everything.',tool:'ChatGPT',toolUse:'Analyses click and conversion data and suggests what to change',video:'how to track affiliate marketing performance'}]},

{id:'content',name:'Content Creation',color:'#2FB6A6',icon:I.cam,age:'13+ (with parent)',
 desc:'Build an audience around something you love, then earn from sponsorships, products or fan support.',
 intro:{what:'You pick a topic, publish consistently on one platform, and build an audience that comes back. The money does not come from the platform at first — it comes from the audience: sponsorships, your own product, affiliate links or memberships.',
 money:'Sponsored posts, affiliate commissions, your own digital product, and later platform ad revenue.',
 cost:'$0–$60. A phone, natural light, and eventually a cheap microphone.',
 time:'6–12 hours a week, consistently',
 income:'Usually nothing for the first six months. With a few thousand real followers in a focused niche, $50–$400 per sponsored post becomes realistic.',
 risk:'Burnout is the real danger — most people quit after a month of low views. Commit to a fixed posting schedule for three months before judging whether it works.',
 fit:'Good if you enjoy the making itself, not only the outcome.',
 legal:'Most platforms require account holders to be 13+, and 18+ for monetisation programmes and payouts — under 18 the payout account is usually a parent\'s. Sponsored content must be disclosed. Never use music, clips or images you do not have the rights to.'},
 videoUrl:'https://www.youtube.com/watch?v=wZILJ034PxA',
 platforms:[
  {n:'YouTube Studio',w:'Where you upload, read analytics and eventually enable monetisation.',u:'https://studio.youtube.com/',p:'Free'},
  {n:'TikTok Creator Center',w:'Trends, sounds and creator programmes in one place.',u:'https://www.tiktok.com/creators/creator-center/',p:'Free'},
  {n:'Instagram Creators',w:'Reels tools, insights and collaboration features.',u:'https://creators.instagram.com/',p:'Free'},
  {n:'CapCut',w:'The editor most short-form creators actually use — captions, trends, templates.',u:'https://www.capcut.com/',p:'Free tier'},
  {n:'Canva',w:'Thumbnails, covers and graphics without design skills.',u:'https://www.canva.com/',p:'Free tier'},
  {n:'Buffer',w:'Schedule posts across platforms so you publish on a fixed rhythm.',u:'https://buffer.com/',p:'Free tier'},
  {n:'Patreon',w:'Memberships and direct fan support once you have a real audience.',u:'https://www.patreon.com/',p:'Free, takes a cut'}],
 steps:[
  {title:'Choose a platform and a niche',text:'One platform, one clear topic. It is far easier to stand out in a narrow niche than to be another general channel.',tool:'Claude',toolUse:'Helps find an angle nobody else is covering',video:'how to choose a content niche'},
  {title:'Plan and film a week at a time',text:'Pick one filming day and shoot several videos back to back, so you are not chasing an idea every single day.',tool:'Notion AI',toolUse:'Builds a weekly content calendar with ready ideas',video:'weekly content batching for creators'},
  {title:'Edit fast with AI tools',text:'Cut silences, add captions, keep the pace tight. Good editing holds viewers far better than an expensive camera.',tool:'Descript',toolUse:'Edits video like a text document, removing filler words automatically',video:'fast video editing for beginners'},
  {title:'Build community, then monetise',text:'Reply to comments, ask your audience what they want, and only then add one income stream — sponsorship, product or affiliate.',tool:'ManyChat',toolUse:'Handles comments and DMs automatically at scale',video:'how creators make money from followers'}]},

{id:'apps',name:'App & Software Building',color:'#7C5CFF',icon:I.code,age:'14+ (16+ to publish)',
 desc:'Build apps, tools or small SaaS products — with AI you no longer need years of coding first.',
 intro:{what:'You build a real product: a mobile app, a web tool, a browser extension or a small SaaS. AI tools now let you go from idea to working prototype in days, even with limited coding experience. You make money from subscriptions, one-time purchases, ads, or by building apps for clients.',
 money:'Subscriptions (the strongest model), one-time purchase, in-app purchases, ads, or client work at a fixed project price.',
 cost:'$0–$120. Most build tools have free tiers; the real costs are the Apple developer account ($99/year) and Google Play ($25 one-time) if you publish to the stores.',
 time:'10–20 hours a week',
 income:'Client work pays fastest — $200–$1,500 per small project. Your own app usually earns nothing for months, then compounds: a tiny tool with 100 subscribers at $5/month is $500/month with almost no extra work.',
 risk:'The classic mistake is building for six months in secret and launching to silence. Show a rough version to real users in week one. Also watch running costs — a free app with heavy usage can start costing you money.',
 fit:'Good if you like solving problems, iterating, and seeing something you built get used.',
 legal:'App stores require developer account holders to be 18+ — under 18 you publish under a parent\'s developer account. If your app collects any user data you need a privacy policy, and stricter rules apply when your users are children (COPPA in the US, GDPR-K in the EU). Never ship code, assets or designs you copied from someone else.'},
 videoUrl:'https://www.youtube.com/watch?v=1rcSMm-gJSY',
 platforms:[
  {n:'Claude Code',w:'Build and edit real codebases by describing what you want in plain language.',u:'https://claude.com/product/claude-code',p:'Paid plan'},
  {n:'Lovable',w:'Describe a web app and get a working, editable React app you can deploy.',u:'https://lovable.dev/',p:'Free tier'},
  {n:'FlutterFlow',w:'Visual builder for real iOS and Android apps, with exportable code.',u:'https://www.flutterflow.io/',p:'Free tier'},
  {n:'Bubble',w:'No-code platform for full web apps with databases and user accounts.',u:'https://bubble.io/',p:'Free tier'},
  {n:'Glide',w:'Turns a spreadsheet into a usable app — the fastest way to ship a first version.',u:'https://www.glideapps.com/',p:'Free tier'},
  {n:'Supabase',w:'Database, authentication and storage for your app, without running a server.',u:'https://supabase.com/',p:'Free tier'},
  {n:'Firebase',w:'Google\'s backend: auth, database, hosting and analytics in one place.',u:'https://firebase.google.com/',p:'Free tier'},
  {n:'Vercel',w:'Deploy a web app to a real URL in minutes.',u:'https://vercel.com/',p:'Free tier'},
  {n:'GitHub',w:'Where your code lives, versioned and backed up. Essential from day one.',u:'https://github.com/',p:'Free'},
  {n:'Expo',w:'Build and test React Native mobile apps on your own phone.',u:'https://expo.dev/',p:'Free tier'},
  {n:'RevenueCat',w:'Handles in-app subscriptions and purchases across iOS and Android.',u:'https://www.revenuecat.com/',p:'Free under $2.5k/mo'},
  {n:'Apple Developer Program',w:'Required to publish on the App Store. Account holder must be 18+.',u:'https://developer.apple.com/programs/',p:'$99/year'},
  {n:'Google Play Console',w:'Required to publish on Google Play. Account holder must be 18+.',u:'https://play.google.com/console/',p:'$25 one-time'}],
 steps:[
  {title:'Find a problem you personally have',text:'The best first app solves something annoying in your own week — a tracker, a calculator, a tool your class needs. Do not start with "an app like Instagram but better".',tool:'Claude',toolUse:'Turns a vague idea into a defined feature list and a v1 scope',video:'how to come up with a good app idea'},
  {title:'Build a rough working version fast',text:'Aim for something usable in one week, not something finished. Ugly and working beats beautiful and imaginary.',tool:'Lovable / Claude Code',toolUse:'Builds a functioning prototype from a plain-language description',video:'build an app with AI in a week'},
  {title:'Put it in front of 10 real users',text:'Give it to ten people who actually have the problem and watch them use it without helping. Everything you need to fix will show up in those ten sessions.',tool:'Google Forms',toolUse:'Collects structured feedback you can actually act on',video:'how to get your first app users feedback'},
  {title:'Launch and charge money',text:'Publish it — store, web link or both — and add a price or subscription. Free users tell you what they like; paying users tell you what matters.',tool:'RevenueCat',toolUse:'Sets up subscriptions and purchases without building billing yourself',video:'how to launch your first app and monetize'}]},

{id:'ecommerce',name:'Your Own Product',color:'#4F9DDE',icon:I.bag,age:'16+',
 desc:'Design or make a product of your own and build a real brand around it.',
 intro:{what:'Unlike dropshipping, the product is yours: you design or make it, buy a small batch, and sell under your own name. Full control over quality, price and brand — and full responsibility too.',
 money:'Higher margins than dropshipping, typically 2.5–4× your production cost, because there is no middleman.',
 cost:'$150–$700 for a small first batch. That money goes out before any comes in.',
 time:'10–20 hours a week',
 income:'Highly variable. A good product with a precise audience can repay the batch in two months; an untested product sits in a box in your room.',
 risk:'The big one is buying stock before proving demand. Order the smallest batch the supplier allows, even if the unit price is worse.',
 fit:'Good if you have a specific product idea and patience for a longer process.',
 legal:'Selling physical goods brings product safety and labelling rules, especially for anything involving cosmetics, food, electronics or children\'s items. Business registration and sales tax handling are required in most places, which means a parent\'s registration if you are under 18.'},
 videoUrl:'https://www.youtube.com/watch?v=MZCWvhB5lic',
 platforms:[
  {n:'Shopify',w:'Your own branded store with payments built in.',u:'https://www.shopify.com/',p:'Paid, free trial'},
  {n:'Etsy',w:'Marketplace with built-in buyers for handmade and design products.',u:'https://www.etsy.com/sell',p:'Listing + transaction fees'},
  {n:'Alibaba',w:'Where most small-batch manufacturing starts. Always order a sample first.',u:'https://www.alibaba.com/',p:'Free to browse'},
  {n:'WooCommerce',w:'Free store software if you already have a WordPress site.',u:'https://woocommerce.com/',p:'Free core'},
  {n:'Looka',w:'Logo and brand kit generated in minutes.',u:'https://looka.com/',p:'Paid'},
  {n:'Stripe',w:'Payment processing for your own site. Account holder must be 18+.',u:'https://stripe.com/',p:'Per transaction'}],
 steps:[
  {title:'Design or make your product',text:'Start with one simple version. Order a single sample and hold it in your hands before anything else — most problems only show up physically.',tool:'Midjourney',toolUse:'Visualises product concepts before you commit to production',video:'how to develop a product from scratch'},
  {title:'Build a brand and a store',text:'Name, logo, one consistent voice. Tell the story behind the product — that is what separates a brand from another shop.',tool:'Looka',toolUse:'Generates a logo and basic brand kit in minutes',video:'how to build a brand for a small business'},
  {title:'Shoot content and sell socially',text:'Film the product in real use, not just on a white background. Real footage stops the scroll far more reliably.',tool:'CapCut AI',toolUse:'Edits short, punchy product content for social platforms',video:'how to shoot product content for social media'},
  {title:'Manage stock and shipping',text:'Track quantities and lead times, and never sell what you do not have. One late order creates a review that stays forever.',tool:'Claude',toolUse:'Builds a simple inventory and order tracking sheet',video:'inventory management for small business'}]},

{id:'pod',name:'Print on Demand',color:'#9B8AFB',icon:I.shirt,age:'15+',
 desc:'Design prints for shirts, mugs and posters — each item is made only after someone buys it.',
 intro:{what:'You upload a design, the platform puts it on products, and when someone orders, the platform prints and ships it. You handle design and marketing only.',
 money:'The gap between your selling price and the printing cost. A shirt costing $12 to print and selling for $28 leaves $16 before advertising.',
 cost:'$0–$40. Uploading is free; the only real cost is advertising if you choose to run it.',
 time:'5–10 hours a week',
 income:'Usually a few scattered sales at first. Finding one precise audience — a hobby, a community, an inside joke — is what turns it into $80–$400/month.',
 risk:'Financial risk is low, but legal risk is real: using characters, logos or images you do not own is the number one reason accounts get shut down.',
 fit:'Good if you like designing and have a recognisable sense of humour or style.',
 legal:'Copyright and trademark law is the whole game here. Fan art, band logos, movie quotes and sports team names are almost always protected. Design only original work, or use assets with a licence that explicitly allows commercial use.'},
 videoUrl:'https://www.youtube.com/watch?v=zpj8jIRQxTk',
 platforms:[
  {n:'Printful',w:'Connects to your store, prints and ships automatically. Strong quality.',u:'https://www.printful.com/',p:'Free to join'},
  {n:'Printify',w:'Network of print providers, usually cheaper with more product choice.',u:'https://printify.com/',p:'Free tier'},
  {n:'Redbubble',w:'Marketplace with its own traffic — upload designs and people find them.',u:'https://www.redbubble.com/',p:'Free'},
  {n:'Teespring (Spring)',w:'Built for creators selling merch to an existing audience.',u:'https://www.spri.ng/',p:'Free'},
  {n:'Etsy',w:'Pairs well with Printful for handmade-style designs.',u:'https://www.etsy.com/sell',p:'Fees per listing'},
  {n:'Canva',w:'Where most first designs get made.',u:'https://www.canva.com/',p:'Free tier'}],
 steps:[
  {title:'Design a print for a specific audience',text:'Pick a narrow group and design something only they would understand. Generic designs do not sell.',tool:'Midjourney',toolUse:'Generates original design concepts and illustrations quickly',video:'how to design t shirts that sell'},
  {title:'Connect a print-on-demand platform',text:'Link your store to a printer that produces and ships automatically, and order one sample to check the print quality yourself.',tool:'Printful',toolUse:'Handles production and shipping without you touching anything',video:'how to connect printful to your store'},
  {title:'Market with real photos',text:'Photograph friends wearing it. Computer mockups look like mockups and convert worse.',tool:'CapCut',toolUse:'Creates short content showing the product being worn',video:'how to market print on demand products'},
  {title:'Keep what sells, expand it',text:'Drop the designs that do not move and make variations of the ones that do, instead of inventing something new every time.',tool:'ChatGPT',toolUse:'Analyses which designs sell and why',video:'scaling a print on demand business'}]},

{id:'freelance',name:'Freelancing',color:'#EF6FA0',icon:I.case,age:'14+ (16+ on most platforms)',
 desc:'Sell a skill — editing, design, writing, code — with zero money upfront.',
 intro:{what:'You sell your time and skill: video editing, graphic design, writing, web building, ad management. The client pays for a defined result.',
 money:'Per project or per hour. Per project is better — as you get faster, you earn more for the same time.',
 cost:'$0. A computer and free tools are enough.',
 time:'Fully flexible — 4 hours a week is a real start',
 income:'This is the fastest path to actual money. A first client within two weeks is realistic, and $300–$1,200/month after a few months is normal.',
 risk:'Clients who do not pay, or who ask for endless revisions. Agree in writing up front: what is included, how many revisions, and when payment happens.',
 fit:'Good if you are already decent at something and want to see money in the short term.',
 legal:'Most freelance platforms require members to be 18+ (some allow 16+ with parental consent) — check before building a profile. Freelance income is taxable income in almost every country, and under 18 it usually has to be handled through a parent. Always use a simple written agreement.'},
 videoUrl:'https://www.youtube.com/watch?v=m97fJxWwiMQ',
 platforms:[
  {n:'Fiverr',w:'Sell packaged services; buyers come to you. Easiest place to get a first review.',u:'https://www.fiverr.com/',p:'Free, takes a cut'},
  {n:'Upwork',w:'Bigger projects and longer client relationships.',u:'https://www.upwork.com/',p:'Free, takes a cut'},
  {n:'Contra',w:'Commission-free freelance platform with a portfolio built in.',u:'https://contra.com/',p:'Free'},
  {n:'Behance',w:'Portfolio site designers and editors actually get hired from.',u:'https://www.behance.net/',p:'Free'},
  {n:'Canva',w:'Design delivery for clients without expensive software.',u:'https://www.canva.com/',p:'Free tier'},
  {n:'Wave',w:'Free invoicing so you look professional and get paid on time.',u:'https://www.waveapps.com/',p:'Free invoicing'}],
 steps:[
  {title:'Pick one skill you already have',text:'Choose the thing you are already good at and turn it into a defined offer: exactly what is included, how long it takes, what it costs.',tool:'Claude',toolUse:'Defines a service package and a sensible beginner price',video:'how to choose a freelance service to sell'},
  {title:'Build a portfolio fast',text:'No clients yet? Make three samples of your own. Nobody asks whether it was a paid job — they ask whether it is good.',tool:'Canva AI',toolUse:'Builds a presentable portfolio in about an hour',video:'how to build a portfolio with no experience'},
  {title:'Land the first client',text:'Message small businesses you already know and offer a starter price in exchange for an honest review. Direct outreach beats posting and waiting.',tool:'ChatGPT',toolUse:'Writes a short outreach message and a simple quote',video:'how to get your first freelance client'},
  {title:'Collect reviews and raise prices',text:'Ask for a written review after every good job. Three reviews let you raise your price without apologising.',tool:'Claude',toolUse:'Drafts a review request and a pricing ladder as you gain experience',video:'how to price freelance services'}]},

{id:'social',name:'Social Media Management',color:'#A8C94A',icon:I.chat,age:'16+',
 desc:'Run social accounts for small businesses on a fixed monthly fee.',
 intro:{what:'Small businesses know they need to post but have no time or skill. You handle it: filming, writing, designing and publishing consistently, for a monthly fee.',
 money:'A monthly retainer — typically $200–$700 per client depending on how much content you produce.',
 cost:'$0. A phone and free design tools are enough.',
 time:'4–8 hours a week per client',
 income:'Predictable and recurring, which is the real advantage. Two steady clients is already $400–$1,200/month.',
 risk:'Promising results you cannot control. Sell consistent, quality content — not a follower count.',
 fit:'Good if you are comfortable talking to business owners and meeting deadlines.',
 legal:'You are handling someone else\'s brand accounts: agree in writing on access, approvals and what happens to the accounts if you stop working together. Never buy followers or engagement — it breaches platform terms and can get the client\'s account penalised.'},
 videoUrl:'https://www.youtube.com/watch?v=y-n1RUbYq6Q',
 platforms:[
  {n:'Meta Business Suite',w:'Manage and schedule Instagram and Facebook for clients from one place.',u:'https://business.facebook.com/',p:'Free'},
  {n:'Buffer',w:'Simple scheduling across platforms with clear reporting.',u:'https://buffer.com/',p:'Free tier'},
  {n:'Later',w:'Visual planner built for Instagram-first clients.',u:'https://later.com/',p:'Free tier'},
  {n:'Metricool',w:'Analytics and reports that make monthly client updates easy.',u:'https://metricool.com/',p:'Free tier'},
  {n:'Canva',w:'Client-ready post design at speed.',u:'https://www.canva.com/',p:'Free tier'},
  {n:'Notion',w:'Content calendars clients can review and approve.',u:'https://www.notion.com/',p:'Free tier'}],
 steps:[
  {title:'Choose the type of business you serve',text:'Pick one category — cafés, barbers, gyms — and learn it deeply. Specialising builds trust much faster.',tool:'Claude',toolUse:'Audits existing accounts and identifies what is missing',video:'how to find social media management clients'},
  {title:'Prepare a pitch and sample work',text:'Make three sample posts for a real business before they ask. It is the fastest way to get a first meeting.',tool:'Canva AI',toolUse:'Designs professional-looking posts quickly',video:'social media proposal for clients'},
  {title:'Plan a month of content',text:'Build a monthly calendar the client approves in advance. It prevents arguments and shows there is a system.',tool:'Notion AI',toolUse:'Builds a content calendar and publishing schedule',video:'how to plan a monthly content calendar'},
  {title:'Report results and keep the client',text:'Send a short monthly summary: what was posted, what performed best, what is next. Consistent reporting is what keeps a retainer alive.',tool:'ChatGPT',toolUse:'Writes a short, clear monthly performance report',video:'social media client reporting'}]},

{id:'courses',name:'Digital Products & Courses',color:'#6C7BD1',icon:I.book,age:'15+',
 desc:'Turn something you already know into a guide you can sell again and again.',
 intro:{what:'You take something you already know — guitar, editing, maths, gaming — and turn it into a structured guide or mini-course. You make it once and sell it indefinitely.',
 money:'Direct sales of a digital product. No production cost per sale, so almost the entire price stays with you.',
 cost:'$0–$30. Screen recording plus a sales platform that takes a small cut.',
 time:'15–30 hours to build, then very little',
 income:'Depends entirely on audience. With no audience, sales are near zero; with a small loyal one, $150–$700/month is realistic.',
 risk:'The classic mistake is spending six months building a huge course nobody wants. Sell first, build second.',
 fit:'Good if you already explain things to people easily.',
 legal:'You must own everything in the course — no copied slides, images, music or text. If you make claims about results, they need to be honest. Payout accounts on most platforms require the holder to be 18+.'},
 videoUrl:'https://www.youtube.com/watch?v=ccIWfbIXSGU',
 platforms:[
  {n:'Gumroad',w:'The simplest way to sell a digital file and get paid.',u:'https://gumroad.com/',p:'Free, takes a cut'},
  {n:'Payhip',w:'Sell ebooks, courses and memberships with a free plan.',u:'https://payhip.com/',p:'Free tier'},
  {n:'Teachable',w:'Full course platform with lessons, quizzes and student progress.',u:'https://teachable.com/',p:'Free tier'},
  {n:'Podia',w:'Courses, downloads and email marketing in one place.',u:'https://www.podia.com/',p:'Paid, free trial'},
  {n:'Notion',w:'Build and structure the course content itself.',u:'https://www.notion.com/',p:'Free tier'},
  {n:'OBS Studio',w:'Free screen recording for lessons.',u:'https://obsproject.com/',p:'Free'}],
 steps:[
  {title:'Pick a topic you actually know',text:'Choose something people have asked you about more than once. A repeated question is the clearest signal of demand.',tool:'Claude',toolUse:'Maps your topic into clear, ordered lessons',video:'how to choose a course topic'},
  {title:'Build a short, focused version',text:'One to two hours of content solving one problem. A giant course intimidates both you and the buyer.',tool:'Notion AI',toolUse:'Organises your material into a clear course structure',video:'how to build a mini course'},
  {title:'Launch and sell it',text:'Put it on a sales platform and write a page that says exactly what the learner will be able to do at the end. That is what sells.',tool:'Gumroad',toolUse:'Hosts the product and handles payment for you',video:'how to sell a digital product online'},
  {title:'Collect feedback and improve',text:'Ask your first ten buyers what was clear and what was not, then update. Version two sells far better.',tool:'ChatGPT',toolUse:'Turns scattered feedback into an ordered improvement list',video:'how to improve an online course'}]},
{id:'websites',name:'Website Building for Businesses',color:'#2FA88A',icon:I.code,age:'15+',
 desc:'Build simple websites for local businesses that don\'t have one yet, using AI website builders instead of coding by hand.',
 intro:{what:'Millions of small businesses — a barber, a tutor, a local bakery — still have no website or a badly outdated one. You use AI website builders to produce a clean, working site in hours instead of weeks, then sell the finished result (and often ongoing hosting/updates) to the business owner.',
 money:'A one-time build fee per site ($150–$800 depending on complexity), often plus a small monthly fee for hosting and updates ($20–$60/month) — which turns into recurring income across multiple clients.',
 cost:'$0–$30/month. Most AI website builders have a free tier to build and demo; a paid plan is usually needed only once a client says yes.',
 time:'5–10 hours per site once you have a repeatable process',
 income:'A first client is realistic within a few weeks of outreach. Five clients on a small monthly hosting fee is $100–$300/month recurring, on top of the one-time build fees.',
 risk:'Promising a finished, polished site for almost nothing undervalues real work — price for your time, not just the AI tool’s speed. Also confirm in writing who owns the domain and content if the client ever wants to leave.',
 fit:'Good if you like a bit of both design and sales, and don\'t mind reaching out to real local business owners.',
 legal:'This is a service business like freelancing: most invoicing and business-registration rules apply the same way, and under 18 a parent typically needs to be the invoicing/registered party. Always get a simple written agreement on price, revisions, and who owns the finished site and domain.'},
 videoUrl:'https://www.youtube.com/watch?v=H1hqWz6PyQY',
 platforms:[
  {n:'Durable',w:'Generates a complete small-business website from a one-line description in under a minute — the fastest way to build a first draft.',u:'https://durable.co/',p:'Free tier'},
  {n:'10Web',w:'AI website builder built specifically for small businesses, with real WordPress underneath for flexibility later.',u:'https://10web.io/',p:'Free tier'},
  {n:'Hostinger Website Builder',w:'AI website generator bundled with affordable hosting — good default if the client needs hosting too.',u:'https://www.hostinger.com/website-builder',p:'Paid, free trial'},
  {n:'Framer',w:'AI-assisted, highly polished website builder popular for modern-looking small business sites.',u:'https://www.framer.com/',p:'Free tier'},
  {n:'Wix',w:'Wix ADI generates a starting site from a short questionnaire, then you customise visually.',u:'https://www.wix.com/',p:'Free tier'},
  {n:'Webflow',w:'More design control for clients who want something more custom, still much faster than hand-coding.',u:'https://webflow.com/',p:'Free tier'},
  {n:'Google Business Profile',w:'Where most local customers actually find a business — pairs with every site you build.',u:'https://www.google.com/business/',p:'Free'}],
 steps:[
  {title:'Find businesses that need a website',text:'Search Google Maps for local businesses with no website link, or with one that looks years out of date. These are your warmest leads — they already know they need one.',tool:'Claude',toolUse:'Drafts a short outreach message tailored to each business type',video:'find local business leads no website'},
  {title:'Build a free sample before you pitch',text:'Use an AI builder to create a rough, real site for one business — even before they ask. Showing up with something finished converts far better than a generic pitch.',tool:'Durable',toolUse:'Generates a full draft site from a one-line business description',video:'ai website builder demo'},
  {title:'Present it and agree on scope in writing',text:'Show the demo, agree a price, and write down what is included: pages, revisions, who owns the domain, and any ongoing hosting fee.',tool:'Claude',toolUse:'Drafts a simple one-page agreement covering price and ownership',video:'freelance website contract basics'},
  {title:'Deliver, connect the domain, and offer upkeep',text:'Publish the site, connect their domain, and offer a small monthly fee for hosting and occasional updates — this is what turns one-time projects into recurring income.',tool:'Hostinger',toolUse:'Handles domain connection and hosting for the finished site',video:'connect custom domain to website'}
 ]}
];

const MILESTONES=['Just started 🚀','Built my store/page','Published first content','First sale or client 🎉','Passed $500','A mistake I learned from','Stuck — need advice'];

const TEMPLATES=[
{name:'Before / After hook',platform:'TikTok · Reels',why:'The brain stops on visual change. Show the result first, then rewind and explain.',
 beats:[['0-3s','Show the finished "after", no talking'],['3-10s','"Here is what it looked like a week ago"'],['10-25s','Three quick steps that got you there'],['End','"Want the full steps? Comment [word]"']],
 script:'Look how this ended up.\nA week ago it looked like this.\nI did three things:\n1. ...\n2. ...\n3. ...\nWant the full breakdown? Comment "steps".',
 tip:'Film the "after" from the exact same angle as the "before" — the comparison only works if the framing matches.'},
{name:'POV',platform:'TikTok · Reels',why:'Puts the viewer inside the moment, which creates instant identification and shares.',
 beats:[['0-2s','On-screen text: "POV: you [situation]"'],['2-12s','Act out the moment, no explaining'],['12-20s','The twist or the fix — this is where the product enters'],['End','A question that invites comments']],
 script:'POV: you get your first order and you cannot believe it.\n(show the moment)\nWhat I did next changed everything: ...\nAnyone else remember their first one?',
 tip:'The POV text must be readable in two seconds. Seven words maximum.'},
{name:'3 mistakes',platform:'All platforms',why:'Immediate value, so people save it — and saves push distribution hard.',
 beats:[['0-3s','"3 mistakes I made in [topic] that cost me"'],['3-20s','Mistake, why it hurts, what to do instead'],['20-30s','Third mistake — the strongest one'],['End','"Save this before you start"']],
 script:'3 mistakes I made starting [topic]:\n1. [mistake] — do [fix] instead\n2. [mistake] — do [fix] instead\n3. [mistake] — and this one is the expensive one\nSave this before you start.',
 tip:'Put the strongest mistake last, but hint at it in the hook so people stay.'},
{name:'Day in the life',platform:'TikTok · Reels · Stories',why:'Builds personal trust over time. Sells who you are, not what you sell.',
 beats:[['0-3s','"Day in the life of a [what you do] at [age]"'],['3-25s','Four to six short clips with times on screen'],['25-35s','One honest moment — a struggle, not only a win'],['End','"Tomorrow I am trying [thing] — want to see?"']],
 script:'7:30 — check if anything sold overnight\n14:00 — answer customers between classes\n17:00 — film content for the week\n21:00 — nothing sold today, and that is part of it\nTomorrow I am trying something new.',
 tip:'One honest failure clip builds more trust than any success video.'},
{name:'15-second product demo',platform:'All platforms',why:'The most direct way to sell: show what it does instead of explaining it.',
 beats:[['0-2s','The product in action, close up'],['2-10s','The problem it solves, in one sentence'],['10-15s','One surprising second use'],['End','One clear call to action']],
 script:'This fixes something that annoys you every single day.\n[show it being used]\nAnd it also does this, which nobody expects.\nLink in bio.',
 tip:'Skip loud music — the sound of the product being used sells better than a track.'},
{name:'30-day journey',platform:'TikTok · YouTube',why:'A series brings viewers back. Each episode builds curiosity for the next.',
 beats:[['0-3s','"Day [X] of 30 building [goal]"'],['3-20s','What you did today and what happened'],['20-30s','The real numbers — in and out'],['End','"Tomorrow: [specific thing]"']],
 script:'Day 7 of 30 building a business from zero.\nToday I tried [action].\nResult: [real number].\nTomorrow I test [next thing].',
 tip:'Post real numbers, even small ones. Transparency is what builds the audience in this format.'},
{name:'Reply to a comment',platform:'TikTok · Reels',why:'The topic is pre-validated — someone asked, so it is interesting. It also generates more comments.',
 beats:[['0-3s','Show the comment on screen and read it'],['3-20s','An honest, specific answer'],['End','"More questions? Ask below"']],
 script:'Someone asked: "how much money do you actually need to start?"\nThe honest answer is ...\n[real numbers]\nMore questions? Go ahead.',
 tip:'Pick the comment that asks what many people are thinking but not typing.'},
{name:'This vs that',platform:'All platforms',why:'Buying decisions are built from comparisons, so this format leads straight to a sale.',
 beats:[['0-3s','"[option A] vs [option B] — what actually wins"'],['3-20s','Three criteria, a winner in each'],['20-30s','A clear recommendation per type of person'],['End','"Which one would you pick?"']],
 script:'[A] vs [B].\nPrice: ...\nQuality: ...\nEase: ...\nIf you are starting out, go [X]. If you are experienced, [Y].',
 tip:'Say when the cheaper option is enough — that is what makes people trust you.'}];

const EDITING={
 tools:[{n:'CapCut',d:'Phone-first video editing: cuts, auto captions, trending templates. Free and enough for almost everything.'},
 {n:'Canva',d:'Posts, thumbnails, logos and product graphics, with AI that writes and designs for you.'},
 {n:'Descript',d:'Edit video by editing its transcript — delete a word and it disappears from the video. Great for talking-head explainers.'},
 {n:'Adobe Podcast (free)',d:'Cleans background noise and improves recorded audio in one click.'}],
 rules:[['The first three seconds','They decide 80% of the outcome. Open with the most interesting part, never "hey guys, what is up".'],
 ['Always caption','Most people scroll with sound off. No captions means you lost them.'],
 ['Cut every 2–3 seconds','Every cut resets attention. A static shot loses viewers fast.'],
 ['Full-screen 9:16','No square video with black bars. Fill the whole screen.'],
 ['Trending sound, low volume','Music helps distribution, but your voice has to sit on top of it.'],
 ['One call to action','Ask for one thing at the end: comment, save or click. Not three.']],
 flow:['Film 3–5 takes of the hook alone and keep the best one — the hook matters most.',
 'Import to CapCut and cut out every silence and stumble.',
 'Add auto captions and fix the errors (there are always errors).',
 'Add a trending sound from the platform library at 15–25% volume.',
 'Put text on screen in the first second — without it there is no hook.',
 'Export at 1080p and upload from inside the platform app, not through the share sheet.'],
 mistakes:['Music so loud it buries your voice.','Longer than it needs to be — 20 strong seconds beat 60 weak ones.','Posting the identical file to every platform with no adaptation.','Deleting an underperforming video after an hour — distribution sometimes starts two days later.']};

const GLOSSARY=[
['Niche','A focused audience with a shared interest. The narrower the niche, the easier it is to stand out and sell.'],
['Hook','The first three seconds of a video or the first line of a post. Its only job is to stop the scroll.'],
['Conversion','The moment someone does the thing you wanted — buys, signs up, or leaves their details.'],
['CTR','The share of people who saw your ad and clicked it. Below 1% usually means the ad is not interesting enough.'],
['ROAS','Return on ad spend. ROAS 3 means $3 came back for every $1 spent.'],
['CPM','Cost to show an ad to a thousand people. Useful for comparing platforms.'],
['Margin','What is left after all costs. Not what the customer paid — what stays with you.'],
['AOV','Average order value: what a typical customer spends in one purchase. Raising it is the cheapest way to earn more.'],
['Pixel','Tracking code on your site that tells the ad platform who did what. Without it, advertising is blind.'],
['Leads','People who showed interest and left details, but have not bought yet.'],
['Organic vs paid','Organic is reach you did not pay for. Paid is reach you bought. A healthy business uses both.'],
['UGC','User-generated content — looks real, so it converts better than polished ads.'],
['Monetisation','Turning an audience or content into income: sponsorships, products, affiliates or memberships.'],
['Retainer','A fixed monthly fee for ongoing work. The basis of stable freelance and social income.'],
['MRR','Monthly recurring revenue — the number that matters most for apps and subscriptions.'],
['CTA','Call to action — the line that asks the viewer to do one clear thing.']];

const AGE_GUIDE=[
{age:'13–15',title:'Learning and building, no money handling',
 fits:['content','affiliate','apps'],
 what:'At this age almost every platform that pays out requires an adult account holder, so the realistic goal is skill and audience, not revenue. Build the channel, learn to edit, build a first app, learn how ads work. Any money that does appear should run through a parent\'s account.',
 rules:'Social platforms generally require users to be 13+. Payment services (PayPal, Stripe), ad accounts and app store developer accounts require 18+. Affiliate networks mostly require 18+, so a parent applies and supervises.'},
{age:'16–17',title:'Real earning, with a parent as the legal holder',
 fits:['freelance','social','pod','courses','dropship'],
 what:'This is where actual income becomes realistic. Freelancing and social media management pay fastest and need almost no capital. Dropshipping and print on demand work too, as long as a parent holds the store, payment and tax side.',
 rules:'Contracts signed by a minor can generally be voided, so client agreements and supplier contracts should be in a parent\'s name. Income is taxable and usually reported through the parent. Some freelance platforms allow 16+ with documented parental consent — check each one.'},
{age:'18+',title:'Everything, in your own name',
 fits:['ecommerce','dropship','apps','courses','social','freelance','affiliate','pod','content'],
 what:'You can register a business, open payment processing, hold a developer account and sign contracts yourself. Product-based businesses that need real capital and legal responsibility become genuinely available.',
 rules:'You are now personally responsible for tax registration and reporting, consumer law compliance, privacy policies and any contract you sign. This is the point to talk to an accountant once, properly.'}];

const LEGAL=[
{t:'Minors and contracts',d:'In most countries a contract signed by someone under 18 can be voided, and legally significant actions need a parent or guardian\'s consent. In practice: payment processing, supplier agreements and client contracts should be in a parent\'s name. Small everyday purchases typical for your age do not need special approval.'},
{t:'Business registration and tax',d:'Business registration and tax numbers require an adult account holder. Until 18, the standard route is a parent registering and formally operating the business while you run it day to day. Income from a business is taxable and reportable, even when it is small. Before there is steady income, talk to an accountant or your local tax authority once.'},
{t:'Copyright and trademarks',d:'Never use images, music, video, logos or characters that are not yours — not "just in a story", not even with credit. In print on demand this is the single most common reason accounts get closed and legal letters arrive. Use properly licensed libraries, platform-native music, or work you made yourself.'},
{t:'Advertising disclosure',d:'When you are paid, given a free product, or earning a commission for a recommendation, you must disclose it clearly ("paid partnership", "affiliate link"). Hiding it counts as misleading advertising in most jurisdictions. It also pays off: an audience that finds out on its own stops trusting you.'},
{t:'Consumer rights and refunds',d:'Distance selling to consumers comes with a legal right of cancellation in many countries, within defined timeframes. Your store must show accurate product details, total price, delivery times and a clear refund policy. Do not copy a policy from another site — write one that matches what you actually offer.'},
{t:'Customer privacy and data',d:'Names, phone numbers, addresses and emails are personal data with legal protection. Collect only what you need, never share it, and never send marketing without explicit prior consent. Anywhere you collect data, you need a privacy policy. Stricter rules apply if your users are children.'},
{t:'Payments and safety',d:'Take payments only through recognised processors, never a personal transfer from someone you do not know. Never send identity documents, home address or passwords to a "supplier" or a "mentor". A guaranteed-income promise in exchange for an upfront payment is a reliable sign of a scam.'},
{t:'What this is not',d:'Everything here is general explanation, not legal, tax or financial advice. Before any decision with real financial consequences, talk to a parent, and where it matters, to a lawyer or an accountant.'}];

const TERMS=[
{t:'1. Acceptance of these terms',d:'These Terms govern your use of this application. By creating an account or using the app you agree to them in full. If you do not agree, do not use the app.'},
{t:'2. What this service is',d:'The app provides general educational information, guides and software tools about entrepreneurship. It sells no products, guarantees no business outcome, and does not constitute business, legal, tax or financial advice of any kind.'},
{t:'3. Age and parental consent',d:'The app is designed for teenagers. Users under 18 must have the consent of a parent or guardian to use the app, and in particular before any commercial, financial or contractual activity with a third party.'},
{t:'4. No copying of content — restricted use',d:'All guides, lesson text, templates, illustrations, structure and design in this app are owned by its operators and protected by copyright. You may use them for your own personal, non-commercial learning only. You may NOT copy, reproduce, republish, redistribute, scrape, sell, sublicense, translate or repackage any part of the content, and you may NOT use it to build a competing product or to train a machine-learning model, without prior written permission. Violation may result in immediate account termination and legal action.'},
{t:'5. User-generated content',d:'You are responsible for anything you post in the community feed. Do not post identifying details (address, phone number, documents), offensive, misleading or spam content, or anything that infringes a third party\'s rights. You retain ownership of what you post and grant the operators a licence to display it within the app. The operators may remove content and suspend accounts at their discretion, without prior notice.'},
{t:'6. AI-generated output',d:'Some tools in this app generate content using a language model. Such output may be inaccurate, incomplete or inappropriate. Checking it and deciding how to use it is your responsibility alone.'},
{t:'7. No warranty and limitation of liability',d:'The app is provided "as is". The operators are not liable for any direct or indirect damage, financial loss, lost income or any outcome resulting from reliance on information in the app or from business activity undertaken after using it.'},
{t:'8. Third-party links and services',d:'The app links to external sites, videos and tools that it does not control. Their appearance is not an endorsement or a warranty as to their content, terms, pricing or availability. Your use of them is governed by their own terms.'},
{t:'9. Accounts and security',d:'You are responsible for keeping your sign-in credentials secure and for activity under your account. Do not share an account or impersonate another person.'},
{t:'10. Privacy',d:'Personal progress data is stored on your device. Content you publish in the feed is visible to other users of the app. Do not enter sensitive personal information anywhere in the app.'},
{t:'11. Changes and termination',d:'The operators may update these Terms, modify the service or discontinue it at any time. Continued use after an update constitutes acceptance of the updated version.'},
{t:'12. Contact',d:'For questions, content removal or copyright notices: [add operator email address].'}];

// ACCESSIBILITY_STATEMENT now lives in js/legal-pages.js (superseded this draft).

const QUIZ=[
{q:'How much can you invest right now?',opts:[
 {t:'Nothing — only time',s:{freelance:3,affiliate:3,content:2,social:3,courses:2,apps:2}},
 {t:'Up to $80',s:{pod:3,dropship:2,content:2,courses:2,apps:2}},
 {t:'More than $150',s:{dropship:3,ecommerce:3,pod:1,apps:1}}]},
{q:'Which describes you best?',opts:[
 {t:'I create — filming, designing, editing',s:{content:3,pod:3,freelance:2}},
 {t:'I sell — I like persuading and talking',s:{dropship:3,social:3,affiliate:2}},
 {t:'I explain — people ask me things',s:{courses:3,affiliate:2,content:2}},
 {t:'I build — I like making things work',s:{apps:3,ecommerce:2,freelance:2}}]},
{q:'How soon do you want your first dollar?',opts:[
 {t:'As fast as possible',s:{freelance:3,social:3,pod:1}},
 {t:'A few months is fine',s:{dropship:2,ecommerce:2,courses:2,pod:2,apps:2}},
 {t:'No rush, building long term',s:{content:3,affiliate:3,apps:2}}]},
{q:'How much free time do you have weekly?',opts:[
 {t:'Under 5 hours',s:{affiliate:2,pod:2,courses:1}},
 {t:'5–10 hours',s:{freelance:3,social:3,content:2,apps:1}},
 {t:'More than 10 hours',s:{dropship:3,ecommerce:3,apps:3,content:2}}]},
{q:'How old are you?',opts:[
 {t:'13–15',s:{content:3,affiliate:2,apps:3}},
 {t:'16–17',s:{freelance:3,social:3,pod:2,courses:2,dropship:2,apps:2}},
 {t:'18+',s:{dropship:2,ecommerce:3,apps:2,courses:2,freelance:2}}]}];

const CONTENT_TYPES=[
{id:'caption',label:'Post caption',prompt:'Write 3 options for a short social post caption (max 3 lines each)'},
{id:'hook',label:'Video hook',prompt:'Write 5 opening hooks for a short video, one line each'},
{id:'script',label:'Short script',prompt:'Write a 30-45 second video script: hook, three points, call to action'},
{id:'hashtags',label:'Hashtags',prompt:'Suggest 12 hashtags in three groups: broad, niche, trending'},
{id:'bio',label:'Profile bio',prompt:'Write 3 options for a short social profile bio with a call to action'},
{id:'dm',label:'Client outreach',prompt:'Write a short, personal outreach message to a small business owner that does not read like spam'}];

/* ---------- Country-specific legal guides ---------- */
const COUNTRY_LEGAL={
 US:{name:'United States',
  rules:[
  ['Age of majority','18 in nearly all states (19 in Alabama and Nebraska, 21 in Mississippi). Below that, contracts can generally be voided by the minor.'],
  ['Business registration','An LLC or sole proprietorship can technically be filed by a minor in most states, but banks, Stripe and PayPal require an account holder aged 18+ — in practice a parent holds the account.'],
  ['Tax filing','The IRS requires a minor to file if they earn self-employment income over $400 in a year. This is usually handled on the minor\'s own return with a parent\'s help, using an SSN or ITIN.'],
  ['Work permits','Most states do not require a work permit for self-employment (as opposed to being someone else\'s employee), but check your state\'s child labor office if in doubt.'],
  ['Data and children\'s privacy','COPPA restricts collecting personal data from users under 13 without verified parental consent — relevant if your own product or app has young users.']]},
 GB:{name:'United Kingdom',
  rules:[
  ['Age of majority','18. Under the Minors\' Contracts Act 1987, most contracts made by someone under 18 are voidable.'],
  ['Business registration','You can register as a sole trader with HMRC at any age, but a parent usually needs to be involved for a bank account and for contracts with suppliers.'],
  ['Tax filing','Self-employed income above the trading allowance (£1,000/year) must be reported to HMRC via Self Assessment, regardless of age.'],
  ['Consumer law','The Consumer Rights Act 2015 sets rules on product descriptions, quality and refunds for anything you sell to UK consumers.'],
  ['Data protection','UK GDPR applies to any personal data you collect from customers, with extra care required for services aimed at under-13s.']]},
 CA:{name:'Canada',
  rules:[
  ['Age of majority','18 or 19 depending on the province (19 in BC, Ontario, the Atlantic provinces and the territories; 18 elsewhere).'],
  ['Business registration','Sole proprietorships can often be registered by a minor with parental consent in many provinces; banks generally require a parent as co-signer or account holder below the age of majority.'],
  ['Tax filing','The CRA requires reporting self-employment income regardless of age. Filing is usually done on the minor\'s own return, often with a parent\'s help.'],
  ['Consumer protection','Provincial consumer protection acts (e.g. Ontario\'s Consumer Protection Act) set rules on accurate advertising and cancellation rights.'],
  ['Privacy','PIPEDA governs how you may collect and use customer personal information.']]},
 AU:{name:'Australia',
  rules:[
  ['Age of majority','18. Contracts made by a minor are generally not binding unless for necessities.'],
  ['Business registration','An ABN can be registered at any age, but a parent or guardian typically needs to be involved for banking and larger supplier agreements.'],
  ['Tax filing','The ATO requires reporting business income regardless of age. Minors have a different tax-free threshold for "unearned" income, but active business income is generally taxed like any individual\'s.'],
  ['Consumer law','The Australian Consumer Law sets strict rules on guarantees, refunds and accurate advertising — enforced actively by the ACCC.'],
  ['Privacy','The Privacy Act and Australian Privacy Principles apply once your business meets certain thresholds or handles sensitive data.']]},
 IL:{name:'Israel',
  rules:[
  ['Age of majority','18, per the Legal Capacity and Guardianship Law. An action by a minor generally needs a parent or guardian\'s consent to be binding.'],
  ['Business registration','A "עוסק פטור" or "עוסק מורשה" is registered with the Tax Authority by an adult; under 18 a parent registers and formally holds the business.'],
  ['Tax filing','Business income is taxable and reportable regardless of age, typically through the parent\'s handling of the minor\'s tax matters.'],
  ['Consumer protection','חוק הגנת הצרכן sets rules on distance selling, mandatory disclosures and cancellation rights.'],
  ['Privacy','חוק הגנת הפרטיות governs collection and use of customer personal data.']]},
 DE:{name:'Germany',
  rules:[
  ['Age of majority','18. Under §§106-113 BGB, a minor over 7 has limited legal capacity and generally needs a parent\'s (or guardian\'s) consent for contracts beyond small pocket-money purchases.'],
  ['Business registration','A "Gewerbe" registration can be filed by a minor only with formal family court and parental approval in most cases; in practice a parent registers and operates it.'],
  ['Tax filing','Income is reportable to the Finanzamt regardless of age; a "Kleinunternehmer" (small business) VAT exemption may apply below a revenue threshold.'],
  ['Consumer law','The Fernabsatzrecht (distance selling rules) requires a 14-day right of withdrawal, an "Impressum" and clear pricing on anything sold to EU consumers.'],
  ['Data protection','GDPR applies fully, with extra scrutiny for services that could be used by children.']]},
 IN:{name:'India',
  rules:[
  ['Age of majority','18, per the Indian Majority Act. The Indian Contract Act treats agreements made by a minor as void.'],
  ['Business registration','GST registration and a current account generally require the applicant to be 18+; under that age a parent registers and holds the business.'],
  ['Tax filing','Under the Income Tax Act, a minor\'s income is usually clubbed with a parent\'s income for tax purposes, with some exceptions for income from the minor\'s own skill or talent.'],
  ['Consumer protection','The Consumer Protection Act, 2019 and its e-commerce rules require accurate listings and grievance handling for online sellers.'],
  ['Data protection','The Digital Personal Data Protection Act requires verifiable parental consent to process a child\'s (under-18) personal data in many cases.']]},
 FR:{name:'France',
  rules:[
  ['Age of majority','18. Under the Code civil, a minor has limited legal capacity and generally needs parental authorisation ("autorisation parentale") for significant acts.'],
  ['Business registration','A minor can be an "auto-entrepreneur" only with formal parental authorisation and, for full independence, emancipation; otherwise a parent registers and holds the business (URSSAF/SIRENE).'],
  ['Tax filing','Business income must be declared; a minor\'s income is typically attached to the parents\' tax household ("foyer fiscal") unless specific arrangements are made.'],
  ['Consumer law','The Code de la consommation requires clear pricing, a 14-day right of withdrawal on distance sales, and mandatory legal notices on a business website.'],
  ['Data protection','GDPR (RGPD) applies fully; French law requires parental consent for data processing of children under 15.']]},
 BR:{name:'Brazil',
  rules:[
  ['Age of majority','18, per the Civil Code. Minors between 16-18 have limited capacity and generally need parental assistance for contracts.'],
  ['Business registration','A CNPJ (business registration) generally requires an adult; a minor between 16-18 may register with formal parental consent (assistência) in some structures.'],
  ['Tax filing','Business income is reportable to the Receita Federal; a minor\'s tax situation is usually handled jointly with a parent.'],
  ['Consumer protection','The Código de Defesa do Consumidor sets strict rules on advertising, refunds and distance-selling cancellation rights (7-day "arrependimento").'],
  ['Data protection','The LGPD requires specific parental consent to process a child\'s personal data.']]},
 AE:{name:'United Arab Emirates',
  rules:[
  ['Age of majority','18 (Hijri calendar), per UAE civil law. Contracts by minors generally require guardian consent.'],
  ['Business registration','Business licensing (mainland or free zone) requires an adult; a parent or guardian typically holds the trade licence for a minor\'s venture.'],
  ['Tax filing','The UAE has no personal income tax, but VAT registration applies once turnover crosses the threshold, and corporate tax rules apply to many businesses.'],
  ['Consumer protection','UAE consumer protection law requires accurate advertising and dispute mechanisms for online sales.'],
  ['Data protection','The UAE PDPL governs personal data collection and requires safeguards for children\'s data.']]},
 other:{name:'Other / not listed',
  rules:[
  ['Age of majority','Usually 18, but check your country\'s specific age of majority and contract law.'],
  ['Business registration','Most countries require an adult to hold a registered business, a payment processing account and supplier contracts — until then, a parent typically holds these on your behalf.'],
  ['Tax filing','Business income is taxable almost everywhere, including small amounts. Ask a parent to check with your local tax authority.'],
  ['Consumer protection','Most countries require accurate product listings, clear pricing and some form of cancellation or refund right for online sales.'],
  ['Data protection','If you collect any customer data (name, email, address), most countries require a privacy policy and place extra restrictions on data from children.']]}
};

const FLOWS={
 dropship:{nodes:['You list a product','Customer orders','You pay supplier','Supplier ships to customer'],note:'You never hold stock. Your profit is the gap between the two payments, minus advertising.'},
 affiliate:{nodes:['You publish content','Viewer clicks your link','They buy from the brand','Brand pays you commission'],note:'You carry no product, no shipping and no support — only the recommendation and the trust behind it.'},
 content:{nodes:['You publish consistently','Audience grows','Brands or fans pay','You reinvest in content'],note:'The audience is the asset. Income arrives only after it exists, which is why the first months look empty.'},
 apps:{nodes:['You find a real problem','Build a rough version','10 users test it','Launch and charge'],note:'Ship something rough in week one. Every month spent building in private is a month of guessing.'},
 ecommerce:{nodes:['You design the product','Order a small batch','Sell under your brand','Restock what sells'],note:'Money leaves before it arrives. Order the smallest batch possible until demand is proven.'},
 pod:{nodes:['You upload a design','Customer orders','Platform prints it','Platform ships it'],note:'No stock and no upfront cost — but every design must be original, or the account gets closed.'},
 freelance:{nodes:['You define a service','Client agrees in writing','You deliver the work','You get paid and reviewed'],note:'The written agreement is the whole protection: scope, revisions and payment timing.'},
 social:{nodes:['You pitch a business','Monthly plan approved','You publish for them','Monthly report keeps them'],note:'Recurring fee, recurring work. Reporting is what turns one month into twelve.'},
 courses:{nodes:['You pick a known topic','Build a short version','Sell the first copies','Improve from feedback'],note:'Built once, sold many times — but only if an audience already exists or you sell before you build.'}};
